# Generated by Django 5.2.5 on 2025-09-02 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Текст')),
                ('is_published', models.BooleanField(choices=[(1, 'Опубликовано'), (0, 'Черновик')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/news/%Y/%m/%d', verbose_name='Фото')),
                ('top_img', models.ImageField(blank=True, null=True, upload_to='photos/news/%Y/%m/%d', verbose_name='Верхнее фото')),
                ('bottom_img', models.ImageField(blank=True, null=True, upload_to='photos/news/%Y/%m/%d', verbose_name='Нижнее фото')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='myblog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
