# Generated by Django 5.2.5 on 2025-09-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_projects_alter_reviews_options_reviews_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
