# Generated by Django 5.2.5 on 2025-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_reviews_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='organization',
            field=models.CharField(verbose_name='Организация'),
        ),
    ]
