# Generated by Django 5.2.5 on 2025-09-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_alter_reviews_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
        ),
    ]
