# Generated by Django 5.2.5 on 2025-09-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
