# Generated by Django 5.2.5 on 2025-09-06 18:36

import myblog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_alter_projects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_multi',
            field=models.BooleanField(default=False, verbose_name='Мульти слайдер'),
        ),
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, null=True, validators=[myblog.models.validate_phone], verbose_name='Телефон'),
        ),
    ]
