# Generated by Django 5.2.5 on 2025-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_projects_is_multi_alter_site_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='projects',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
